# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-09 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_productfile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfile',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductFile',
        ),
    ]
